version: 2
updates:
  # フロントエンド
  - package-ecosystem: "npm"
    directory: "/frontend/chatbot-console"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/chatbot-ui"
    schedule:
      interval: "weekly"

  # バックエンド
  - package-ecosystem: "pip"
    directory: "/backend/chat-router"
    schedule:
      interval: "weekly"
