name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "✨ Features"
    labels: ["feature"]
  - title: "🐛 Fixes"
    labels: ["bug"]
  - title: "📝 Docs"
    labels: ["docs"]
change-template: "- $TITLE (#$NUMBER)"
