version: '3.8'

services:
  lambda-function:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lambda-api-gateway
    ports:
      - "9000:8080"
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - ./:/var/task:ro
    networks:
      - lambda-network

networks:
  lambda-network:
    driver: bridge