AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ChatRouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 512
      Environment:
        Variables:
          VERSION: "1.0.0"
          CHAT_HISTORY_TABLE: "ChatHistory-dev"
          CHAT_ASSETS_BUCKET: "chat-history-assets-dev"
          CHATBOT_SETTINGS_TABLE: "ChatbotSettingsDB-dev"
          TTL_SECONDS: "86400"
          SLACK_SIGNING_SECRET: ""
          LINE_CHANNEL_SECRET: ""
          TEAMS_SECRET: ""
          CUSTOM_UI_SECRET: ""
          AI_PROCESSING_QUEUE: !Ref AIProcessingQueue
          BEDROCK_REGION: ap-northeast-1
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: GET
        TestEndpoint:
          Type: Api
          Properties:
            Path: /test
            Method: ANY
        WebhookCustomUI:
          Type: Api
          Properties:
            Path: /webhook/custom
            Method: POST
        WebhookLineBot:
          Type: Api
          Properties:
            Path: /webhook/line
            Method: POST
        WebhookSlackBot:
          Type: Api
          Properties:
            Path: /webhook/slack
            Method: POST
        WebhookTeamsBot:
          Type: Api
          Properties:
            Path: /webhook/teams
            Method: POST
        BotSettingsAPI:
          Type: Api
          Properties:
            Path: /api/bots
            Method: ANY
        BotSettingsDetailAPI:
          Type: Api
          Properties:
            Path: /api/bots/{botId}
            Method: ANY
        AuthRegisterAPI:
          Type: Api
          Properties:
            Path: /api/auth/register
            Method: POST
        AuthLoginAPI:
          Type: Api
          Properties:
            Path: /api/auth/login
            Method: POST
        AuthMeAPI:
          Type: Api
          Properties:
            Path: /api/auth/me
            Method: ANY
        AuthLogoutAPI:
          Type: Api
          Properties:
            Path: /api/auth/logout
            Method: POST
        ChatsAPI:
          Type: Api
          Properties:
            Path: /api/chats
            Method: ANY
        ChatsDetailAPI:
          Type: Api
          Properties:
            Path: /api/chats/{chatId}
            Method: ANY
        ChatsMessagesAPI:
          Type: Api
          Properties:
            Path: /api/chats/{chatId}/messages
            Method: GET
        # ユーザー管理API
        BotUsersAPI:
          Type: Api
          Properties:
            Path: /api/bots/{botId}/users
            Method: GET
        BotInviteAPI:
          Type: Api
          Properties:
            Path: /api/bots/{botId}/invite
            Method: POST
        BotUserPermissionAPI:
          Type: Api
          Properties:
            Path: /api/bots/{botId}/users/{userId}
            Method: ANY
        InvitationAPI:
          Type: Api
          Properties:
            Path: /api/invitations/{invitationId}
            Method: GET
        InvitationAcceptAPI:
          Type: Api
          Properties:
            Path: /api/invitations/{invitationId}/accept
            Method: POST
        # AI処理用SQSイベント
        AIProcessingSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt AIProcessingQueue.Arn
            BatchSize: 5
            MaximumBatchingWindowInSeconds: 10


  # AI処理用SQSキュー
  AIProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ai-processing-queue-dev
      VisibilityTimeoutSeconds: 150
      MessageRetentionPeriod: 1209600  # 14日間
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AIProcessingDLQ.Arn
        maxReceiveCount: 3

  # AI処理用デッドレターキュー
  AIProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ai-processing-dlq-dev
      MessageRetentionPeriod: 1209600  # 14日間
